### ISSUE TITLE
Replace `mks://localhost/en` as href value in css-mdn.json

### ISSUE THREAD

**Issue by mejarc** [rgarcia/dochub#42]
The committed file for the MDN CSS data includes several between-page links that are broken.

cf. #29

**Comment by kevinburke** [comment]
Hi Melanie,

This project is no longer maintained, you may want to speak to the prject
maintainers about taking over ownership. The PR's look fine to me.

Best,
Kevin

---

Kevin Burke | 415-723-4116 | www.twilio.com

**Comment by mejarc** [comment]
Hello, Kevin,
Thank you for the clarification! I'll ponder the ownership question.
Enjoy,
Melanie

**Comment by keunwoo** [comment]
Re: ownership, if you look at the network graph:
https://github.com/rgarcia/dochub/network
then you'll see that niesc and I are also hacking on dochub forks intermittently.  It would be nice to get dochub into a more collective-ownership mode, for example by setting up a github organization so that multiple people can approve commits, and we can perhaps unfork all our improvements.  If you're interested in working together on this, I can throw some cycles into it.

OTOH, dochub has probably languished because the alternatives have improved a lot since 2010. Mozilla is slowly improving MDN and there is now a weekly tarball of the full rendered MDN site:
https://developer.mozilla.org/en-US/docs/Project:MDN/About#Result_form
Also there are now fairly popular native apps which fill dochub's niche on OS X, Linux, and Windows:
http://kapeli.com/dash
http://zealdocs.org/
If these serve your needs, then you might find adopting them easier than signing up to improve dochub ;).

**Comment by rgarcia** [comment]
Sorry for the radio silence. @vecter and I have both moved on from dochub to other projects. @keunwoo I agree with you on all counts. I think Dash is a great alternative. The downsides of Dash in my view: it costs money, it's only for Mac, and it's not open source. If I had time to invest in dochub again I'd love to convert it to read Dash docsets. A free/open-source/web-based version of Dash would be pretty cool, and a lot easier to maintain than a set of scrapers.
